version: '3'

services:
#  mysql:
#    image: mysql:5.6
#    environment:
#      - MYSQL_ROOT_PASSWORD=${DB_PASSWD}
#      - MYSQL_DATABASE=${DB_NAME}
#    volumes:
#      - ./volumes/mysql:/var/lib/mysql
#      - ./docker/mysql:/etc/mysql/conf.d
#    ports:
#      - ${DB_PORT}:3306
#
#  rabbitmq:
#    image: rabbitmq:management
#    environment:
#      - RABBITMQ_DEFAULT_USER=${MQ_USER}
#      - RABBITMQ_DEFAULT_PASS=${MQ_PASS}
#    ports:
#      - ${MQ_WEB_PORT}:15672
#      - ${MQ_CONNECT_PORT}:5672
#
#  redis:
#    image: redis:4-alpine
#    ports:
#      - ${REDIS_PORT}:6379


  consul-salve-1: &consul-salve
    image: consul:latest
    networks:
      - consul-network
    command: "agent -server -retry-join consul-master -client 0.0.0.0"

  consul-salve-2:
    <<: *consul-salve

  consul-master:
    <<: *consul-salve
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  nomad-server:
    build: ./docker/nomad-server/
    command: "agent -config /nomad/config/server.hcl"
    networks:
      - consul-network
    depends_on:
      - consul-master
    ports:
      - "4646:4646"
      - "4647:4647"
      - "4648:4648"

  nomad-client-checker:
    build: ./docker/nomad-client/
    networks:
      - consul-network
    depends_on:
      - nomad-server
    volumes:
      - ./project/:/nomad/go/
    command: "agent -config /nomad/config/client-checker.hcl"

  nomad-client-fetcher:
    build: ./docker/nomad-client/
    networks:
      - consul-network
    depends_on:
      - nomad-server
    volumes:
      - ./project/:/nomad/go/
    command: "agent -config /nomad/config/client-fetcher.hcl"

networks:
  consul-network: